<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="PersonalDiary.Services\PersonalDiary.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="PersonalDiary.Services\**" />
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="PersonalDiary.Services\**" />
    <EmbeddedResource Remove="Services\**" />
    <Content Remove="PersonalDiary.Services\**" />
    <Content Remove="Services\**" />
    <None Remove="PersonalDiary.Services\**" />
    <None Remove="Services\**" />
    <ProjectReference Include="PersonalDiary.Services\PersonalDiary.Services.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.0" />
  </ItemGroup>

</Project>
